"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { Shield, Server, Leaf, FileDown, CheckCircle2, Copy, ArrowRight, Loader2 } from "lucide-react";
import { jsPDF } from "jspdf";
import { Separator } from "@/components/ui/separator";

export default function RegisterPage() {
  const [formData, setFormData] = useState({
    ownerName: "",
    nodeName: "",
    nodeType: "WAREHOUSE",
  });
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<any>(null);
  const { toast } = useToast();
  const router = useRouter();

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      const res = await fetch("/api/nodes/register", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(formData),
      });

      if (res.ok) {
        const data = await res.json();
        setResult(data);
        toast({
          title: "Registration Successful",
          description: `Node ${formData.nodeName} has been recorded in the grid.`,
        });
      } else {
        throw new Error("Registration failed");
      }
    } catch (err) {
      toast({
        title: "Registration Error",
        description: "Failed to connect to the central shield API.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const generatePDF = () => {
    if (!result) return;

    const doc = new jsPDF();
    const { deviceId, apiKey } = result;
    const { nodeName, nodeType } = formData;

    // Header
    doc.setFillColor(15, 23, 42); // slate-950
    doc.rect(0, 0, 210, 40, "F");
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("SJS ECO-SHIELD GRID", 20, 25);
    doc.setFontSize(10);
    doc.text("Official Node Configuration Blueprint", 20, 32);

    // Node Info
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(16);
    doc.text("Device Credentials", 20, 55);
    
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`Node Name: ${nodeName}`, 20, 65);
    doc.text(`Environment: ${nodeType}`, 20, 72);

    // Credentials Box
    doc.setDrawColor(200, 200, 200);
    doc.setFillColor(248, 250, 252); // slate-50
    doc.roundedRect(20, 80, 170, 40, 3, 3, "FD");

    doc.setFont("courier", "bold");
    doc.setFontSize(14);
    doc.text(`DEVICE ID: ${deviceId}`, 30, 95);
    doc.text(`API KEY:   ${apiKey}`, 30, 105);

    // Instructions
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("Hardware Configuration", 20, 135);
    
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    
    if (nodeType === "WAREHOUSE") {
      doc.text("Sensors Required: 2x DHT11", 20, 145);
      doc.text("- Internal DHT11: Data Pin -> ESP32 Pin 4", 25, 155);
      doc.text("- External DHT11: Data Pin -> ESP32 Pin 14", 25, 162);
      doc.text("- Fan Relay: Control Pin -> ESP32 Pin 5 (Active Low)", 25, 169);
    } else {
      doc.text("Sensors Required: Soil Moisture, MQ135", 20, 145);
      doc.text("- Soil Moisture: Analog Pin -> ESP32 Pin 35", 25, 155);
      doc.text("- Air Quality (MQ135): Analog Pin -> ESP32 Pin 34", 25, 162);
      doc.text("- Pump Relay: Control Pin -> ESP32 Pin 5 (Active Low)", 25, 169);
    }

    // API Reference
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text("Cloud API Endpoints", 20, 190);
    
    doc.setFontSize(10);
    doc.setFont("courier", "normal");
    doc.text("POST /api/telemetry", 20, 200);
    doc.text("Headers:", 25, 210);
    doc.text(`x-device-id: ${deviceId}`, 30, 217);
    doc.text(`x-api-key:    ${apiKey}`, 30, 224);

    // Footer
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text("Generated by SJS Dashboard Automated Provisioning System", 105, 280, { align: "center" });

    doc.save(`${nodeName.toLowerCase().replace(/\s+/g, "_")}_config.pdf`);
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast({
      title: "Copied",
      description: "Credential copied to clipboard.",
    });
  };

  return (
    <div className="min-h-screen bg-tactical-bg text-slate-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,rgba(197,255,201,0.05),transparent_50%)]" />
      
      <AnimatePresence mode="wait">
        {!result ? (
          <motion.div
            key="form"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95 }}
            transition={{ duration: 0.4 }}
            className="w-full max-w-lg z-10"
          >
            <Card className="bg-tactical-surface border-white/5 backdrop-blur-xl shadow-2xl overflow-hidden relative border-b-2 border-r-2 border-white/10">
              <div className="absolute top-0 right-0 p-8 text-tactical-accent/5 pointer-events-none">
                <Shield size={120} />
              </div>

              <CardHeader className="pb-8">
                <div className="flex items-center gap-3 mb-2">
                  <div className="p-2 rounded-lg bg-tactical-accent/10 text-tactical-accent">
                    <Shield size={20} />
                  </div>
                  <span className="text-xs font-bold tracking-[0.2em] text-tactical-accent uppercase">System Enrollment</span>
                </div>
                <CardTitle className="text-3xl font-bold tracking-tight text-white mb-2 headline-font uppercase">Secure Registration</CardTitle>
                <CardDescription className="text-secondary">
                  Provision new hardware nodes and generate secure credentials for the Eco-Shield grid.
                </CardDescription>
              </CardHeader>

              <form onSubmit={handleRegister}>
                <CardContent className="space-y-6">
                  <div className="space-y-2">
                    <Label htmlFor="node_name" className="text-secondary font-bold uppercase text-[10px] tracking-widest">Target Node Name</Label>
                    <Input 
                      id="node_name"
                      placeholder="e.g. Warehouse Zone A"
                      value={formData.nodeName}
                      onChange={(e) => setFormData({...formData, nodeName: e.target.value})}
                      className="bg-black/40 border-white/10 focus:border-tactical-accent/50 transition"
                      required
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="ownerName" className="text-secondary font-bold uppercase text-[10px] tracking-widest">Operator/Owner Name</Label>
                    <Input 
                      id="ownerName"
                      placeholder="e.g. Admin User"
                      value={formData.ownerName}
                      onChange={(e) => setFormData({...formData, ownerName: e.target.value})}
                      className="bg-black/40 border-white/10 focus:border-tactical-accent/50 transition"
                      required
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="nodeType" className="text-secondary font-bold uppercase text-[10px] tracking-widest">Operational Environment</Label>
                    <Select 
                      value={formData.nodeType} 
                      onValueChange={(val) => setFormData({...formData, nodeType: val})}
                    >
                      <SelectTrigger className="bg-black/40 border-white/10 focus:border-tactical-accent/50">
                        <SelectValue placeholder="Select Environment" />
                      </SelectTrigger>
                      <SelectContent className="bg-tactical-high border-white/10 text-primary">
                        <SelectItem value="WAREHOUSE" className="focus:bg-tactical-accent/10 focus:text-tactical-accent">
                          <div className="flex items-center gap-2">
                            <Server size={14} /> Warehouse Controller
                          </div>
                        </SelectItem>
                        <SelectItem value="FIELD" className="focus:bg-tactical-accent/10 focus:text-tactical-accent">
                          <div className="flex items-center gap-2">
                            <Leaf size={14} /> Agricultural Field Monitor
                          </div>
                        </SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </CardContent>

                <CardFooter className="pt-4 pb-8">
                  <Button 
                    type="submit" 
                    className="w-full bg-tactical-accent text-black hover:bg-tactical-accent/90 shadow-lg shadow-tactical-accent/5 group font-black uppercase tracking-widest"
                    disabled={loading}
                  >
                    {loading ? (
                      <Loader2 size={18} className="animate-spin mr-2" />
                    ) : (
                      <ArrowRight size={18} className="mr-2 group-hover:translate-x-1 transition" />
                    )}
                    Generate Security Key
                  </Button>
                </CardFooter>
              </form>
            </Card>
          </motion.div>
        ) : (
          <motion.div
            key="success"
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="w-full max-w-xl z-10"
          >
            <Card className="bg-tactical-surface border-tactical-accent/30 backdrop-blur-xl shadow-2xl overflow-hidden border-b-2 border-r-2 border-tactical-accent/20">
              <CardHeader className="text-center pb-2 pt-10">
                <div className="flex justify-center mb-4">
                  <div className="w-16 h-16 rounded-full bg-tactical-accent/10 flex items-center justify-center text-tactical-accent border border-tactical-accent/20">
                    <CheckCircle2 size={32} />
                  </div>
                </div>
                <CardTitle className="text-3xl font-black tracking-tight text-white uppercase headline-font">Secure Provisioning Complete</CardTitle>
                <CardDescription className="text-secondary mt-2 uppercase tracking-wide text-[10px] font-bold">
                  Infrastructure records updated. Flash the credentials below to your hardware.
                </CardDescription>
              </CardHeader>

              <CardContent className="space-y-6 py-10 px-10">
                <div className="space-y-4">
                  <div className="bg-black/40 p-6 rounded-2xl border border-white/5 group hover:border-tactical-accent/30 transition relative">
                    <Label className="text-[9px] uppercase tracking-widest text-secondary font-black mb-2 block font-mono">Hardware Device ID</Label>
                    <div className="flex items-center justify-between">
                      <code className="text-tactical-accent font-mono text-lg">{result.deviceId}</code>
                      <Button variant="ghost" size="icon" onClick={() => copyToClipboard(result.deviceId)} className="text-secondary hover:text-tactical-accent">
                        <Copy size={16} />
                      </Button>
                    </div>
                  </div>

                  <div className="bg-black/40 p-6 rounded-2xl border border-white/5 group hover:border-tactical-accent/30 transition">
                    <Label className="text-[9px] uppercase tracking-widest text-secondary font-black mb-2 block font-mono">Encrypted API Key</Label>
                    <div className="flex items-center justify-between">
                      <code className="text-tactical-accent font-mono text-lg">{result.apiKey}</code>
                      <Button variant="ghost" size="icon" onClick={() => copyToClipboard(result.apiKey)} className="text-secondary hover:text-tactical-accent">
                        <Copy size={16} />
                      </Button>
                    </div>
                  </div>
                </div>

                <div className="bg-tactical-accent/5 p-4 rounded-xl border border-tactical-accent/20 flex gap-4 items-center">
                  <div className="text-tactical-accent"><FileDown size={24} /></div>
                  <div className="text-[10px] text-secondary leading-relaxed font-bold uppercase tracking-wide">
                    Download the <strong className="text-tactical-accent">Registration Blueprint PDF</strong> for official wiring diagrams, sensor pinouts, and cloud sync instructions.
                  </div>
                </div>
              </CardContent>

              <CardFooter className="bg-black/40 border-t border-white/5 flex gap-3 p-8">
                <Button 
                  onClick={() => router.push("/")} 
                  variant="outline" 
                  className="flex-1 border-white/10 text-secondary hover:bg-tactical-high hover:text-primary uppercase font-black tracking-widest text-[10px]"
                >
                  Return to Grid
                </Button>
                <Button 
                  onClick={generatePDF} 
                  className="flex-1 bg-white text-black hover:bg-slate-100 font-black uppercase tracking-widest text-[10px]"
                >
                  <FileDown size={18} className="mr-2" />
                  Get Blueprint (PDF)
                </Button>
              </CardFooter>
            </Card>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
